global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: [ "localhost:9091", "gateway:9091" ]
  - job_name: "api"
    static_configs:
      - targets: [ "localhost:8080", "api:8080" ]
