[package]
name = "aeri-api"
version = "0.1.0"
edition = "2024"

[dependencies]
colourful-logger = "2.0.1"
actix-web = "4.9.0"
reqwest = { version = "0.12.12", features = ["json", "socks"] }
serde_json = "1.0.139"
serde = { version = "1.0.218", features = ["derive"] }
lazy_static = "1.5.0"
dotenvy = "0.15.7"
redis = { version = "0.29.0", features = ["aio", "streams", "tokio-comp"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
rand = "0.9.0"
num_cpus = "1.16.0"
strsim = "0.11.1"
futures = "0.3.31"
actix-cors = "0.7.0"
prometheus-client = "0.23.1"
